import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "@/app/page.module.css";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.main}>
      <Navbar menuLabels={["認識寶嚴", "最新消息", "年度課程", "法務及活動", "法寶流通/下載", "捐款護持", "我的課程"]} onClick={undefined} className={""} label={""}></Navbar>
        {children}
        </body>
    </html>
  );
}
